# Generated by Django 4.0.3 on 2022-04-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='strip_id',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
